#pragma once

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE    true

#define POWER_CTRL GPIO_NUM_9
#define LED_G GPIO_NUM_43
#define SD_MISO GPIO_NUM_17
#define SD_SCK GPIO_NUM_16
#define SD_MOSI GPIO_NUM_38

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_42
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_39
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_40
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_15
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_41

#define AUDIO_CODEC_PA_PIN      GPIO_NUM_4
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_2
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_1

#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR ES7210_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define DISPLAY_WIDTH 360
#define DISPLAY_HEIGHT 360
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define QSPI_LCD_HOST SPI2_HOST
#define QSPI_LCD_BIT_PER_PIXEL 16
#define QSPI_PIN_NUM_LCD_PCLK GPIO_NUM_18
#define QSPI_PIN_NUM_LCD_CS GPIO_NUM_14
#define QSPI_PIN_NUM_LCD_DATA0 GPIO_NUM_46
#define QSPI_PIN_NUM_LCD_DATA1 GPIO_NUM_13
#define QSPI_PIN_NUM_LCD_DATA2 GPIO_NUM_11
#define QSPI_PIN_NUM_LCD_DATA3 GPIO_NUM_12
#define QSPI_PIN_NUM_LCD_RST GPIO_NUM_3
#define QSPI_PIN_NUM_LCD_BL GPIO_NUM_44

#define OPUS_FRAME_DURATION_MS 60

#define ECHOEAR_STARTUP_GIF_PATH "/sdcard/startup.gif"
#define ECHOEAR_STARTUP_WAV_PATH "/sdcard/startup.wav"
#define ECHOEAR_TEST_BIN_PATH "/sdcard/test.bin"
