/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SPIFFS_DATA_FILES           3
#define MMAP_SPIFFS_DATA_CHECKSUM        0x38CD

enum MMAP_SPIFFS_DATA_LISTS {
    MMAP_SPIFFS_DATA_NORMAL1_BIN = 0,        /*!< normal1.bin */
    MMAP_SPIFFS_DATA_NORMAL2_BIN = 1,        /*!< normal2.bin */
    MMAP_SPIFFS_DATA_NORMAL3_BIN = 2,        /*!< normal3.bin */
};
